[phases.setup]
nixPkgs = [
    "nodejs-18_x",
    "nodePackages.pnpm",
    "python311",
    "python311Packages.pip",
    "gcc",
    "gfortran",
    "blas",
    "lapack",
    "openblas",
    "zlib",
    "stdenv.cc.cc.lib",
    "wget"
]

[phases.install]
cmds = [
    "pnpm install --frozen-lockfile",
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node dist/index.js"
