[phases.setup]
nixPkgs = ["nodejs-18_x", "nodePackages.pnpm", "python311", "python311Packages.pip", "gcc", "stdenv.cc.cc.lib", "wget"]

[phases.install]
cmds = [
    "pip install numpy pandas yfinance scipy scikit-learn xgboost lightgbm arch TA-Lib requests fastdtw --break-system-packages",
    "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node dist/index.js"
